export const HAND_TYPE = /** @type {const} */ ({
  HIGH_CARD: "HIGH_CARD",
  PAIR: "PAIR",
  TWO_PAIR: "TWO_PAIR",
  THREE_OF_A_KIND: "THREE_OF_A_KIND",
  STRAIGHT: "STRAIGHT",
  FLUSH: "FLUSH",
  FULL_HOUSE: "FULL_HOUSE",
  FOUR_OF_A_KIND: "FOUR_OF_A_KIND",
  FIVE_OF_A_KIND: "FIVE_OF_A_KIND",
  STRAIGHT_FLUSH: "STRAIGHT_FLUSH",
  ROYAL_FLUSH: "ROYAL_FLUSH"
});

export const HAND_LABEL = /** @type {const} */ ({
  [HAND_TYPE.HIGH_CARD]: "HIGH CARD",
  [HAND_TYPE.PAIR]: "PAIR",
  [HAND_TYPE.TWO_PAIR]: "TWO PAIR",
  [HAND_TYPE.THREE_OF_A_KIND]: "THREE OF A KIND",
  [HAND_TYPE.STRAIGHT]: "STRAIGHT",
  [HAND_TYPE.FLUSH]: "FLUSH",
  [HAND_TYPE.FULL_HOUSE]: "FULL HOUSE",
  [HAND_TYPE.FOUR_OF_A_KIND]: "FOUR OF A KIND",
  [HAND_TYPE.FIVE_OF_A_KIND]: "FIVE OF A KIND",
  [HAND_TYPE.STRAIGHT_FLUSH]: "STRAIGHT FLUSH",
  [HAND_TYPE.ROYAL_FLUSH]: "ROYAL FLUSH"
});

export const HAND_BASE_SCORE = /** @type {const} */ ({
  [HAND_TYPE.HIGH_CARD]: 0,
  [HAND_TYPE.PAIR]: 100,
  [HAND_TYPE.TWO_PAIR]: 250,
  [HAND_TYPE.THREE_OF_A_KIND]: 400,
  [HAND_TYPE.STRAIGHT]: 500,
  [HAND_TYPE.FLUSH]: 650,
  [HAND_TYPE.FULL_HOUSE]: 800,
  [HAND_TYPE.FOUR_OF_A_KIND]: 1200,
  [HAND_TYPE.FIVE_OF_A_KIND]: 4000,
  [HAND_TYPE.STRAIGHT_FLUSH]: 2000,
  [HAND_TYPE.ROYAL_FLUSH]: 4000
});

export const HAND_PRIORITY = /** @type {const} */ ({
  [HAND_TYPE.FIVE_OF_A_KIND]: 10,
  [HAND_TYPE.ROYAL_FLUSH]: 9,
  [HAND_TYPE.STRAIGHT_FLUSH]: 8,
  [HAND_TYPE.FOUR_OF_A_KIND]: 7,
  [HAND_TYPE.FULL_HOUSE]: 6,
  [HAND_TYPE.FLUSH]: 5,
  [HAND_TYPE.STRAIGHT]: 4,
  [HAND_TYPE.THREE_OF_A_KIND]: 3,
  [HAND_TYPE.TWO_PAIR]: 2,
  [HAND_TYPE.PAIR]: 1,
  [HAND_TYPE.HIGH_CARD]: 0
});

